# Generated by Django 4.1.7 on 2023-04-19 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_alter_comment_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='post_text',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
