# Generated by Django 4.1.7 on 2023-05-11 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_alter_answer_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='room',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='polls.room'),
        ),
    ]
