# Generated by Django 4.1.7 on 2023-06-10 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_remove_profile_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='color',
        ),
    ]
