# Generated by Django 4.1.7 on 2023-06-22 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_notification_viewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='text',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
