# Generated by Django 4.1.7 on 2023-06-17 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docbook', '0002_alter_article_text_alter_item_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(max_length=15000),
        ),
    ]
